/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interfaz;

import BD.Conexion;
import Clases.Empleado;
import static java.lang.Integer.parseInt;
import javax.swing.JOptionPane;
import java.sql.Connection;


/**
 *
 */
public class PantallaCargarEmpleado extends javax.swing.JFrame {

    /**
     * Creates new form JframeEmpleado
     */
    public PantallaCargarEmpleado() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    public void Cargar (){
    
        if(jTFnom.getText().equals("")|| jTFdni.getText().equals("") || jTFlegajo.getText().equals("") || jTFtel.getText().equals("") || jTFdir.getText().equals("")){
            JOptionPane.showMessageDialog(this, "Complete todos los campos.");}
          
        Empleado emp = new Empleado(jTFnom.getText(), parseInt(jTFdni.getText()),jTFlegajo.getText(), jTFtel.getText(), jTFdir.getText(), (String) jCBcargo.getSelectedItem());
         
        Conexion con  = new Conexion();//creo la conexion
        
        try{
             Connection connect  = con.Conectar();//abro la conexion
             java.sql.Statement st = connect.createStatement(); //objeto para realizar la consulta
             String sql = "INSERT INTO empleados(edni, enombre, elegajo, etel, edireccion, ecargo) VALUES ("+emp.getDni()+", '"+emp.getNombre()+"', '"+emp.getLegajo()+"', '"+emp.getTelefono()+"', '"+emp.getDireccion()+"', '"+emp.getCargo()+"');";
             st.execute(sql);
             JOptionPane.showMessageDialog(this, "Carga exitosa.");
             st.close();
             connect.close();
         JOptionPane.showMessageDialog(this, "Carga exitosa.");
        }catch(Exception e)
        {
        JOptionPane.showMessageDialog(this, "Carga Fallida.");
        }

    }
         
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTFnom = new javax.swing.JTextField();
        jTFdni = new javax.swing.JTextField();
        jTFlegajo = new javax.swing.JTextField();
        jTFtel = new javax.swing.JTextField();
        jTFdir = new javax.swing.JTextField();
        JLnombre = new javax.swing.JLabel();
        jLdni = new javax.swing.JLabel();
        jLlegajo = new javax.swing.JLabel();
        jLtel = new javax.swing.JLabel();
        jLdireccion = new javax.swing.JLabel();
        jLcargo = new javax.swing.JLabel();
        jBagregar = new javax.swing.JButton();
        jCBcargo = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        JLnombre.setText("Nombre");

        jLdni.setText("DNI");

        jLlegajo.setText("Legajo");

        jLtel.setText("Teléfono");

        jLdireccion.setText("Dirección");

        jLcargo.setText("Cargo");

        jBagregar.setText("Agregar");
        jBagregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBagregarActionPerformed(evt);
            }
        });

        jCBcargo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Recolector", "Chofer" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(JLnombre, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLcargo)
                    .addComponent(jLdireccion, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLtel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLlegajo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLdni, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTFtel)
                    .addComponent(jTFdir)
                    .addComponent(jTFdni)
                    .addComponent(jTFlegajo)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jTFnom, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jCBcargo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(64, 64, 64))
            .addGroup(layout.createSequentialGroup()
                .addGap(151, 151, 151)
                .addComponent(jBagregar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(17, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTFnom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JLnombre))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTFdni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLdni))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTFlegajo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLlegajo))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTFtel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLtel))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTFdir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLdireccion))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLcargo)
                    .addComponent(jCBcargo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jBagregar)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBagregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBagregarActionPerformed
        // TODO add your handling code here:
        Cargar();
          jTFnom.setText("");
         jTFdni.setText("");
         jTFlegajo.setText("");
         jTFtel.setText("");
         jTFdir.setText("");
        this.setVisible(false);
    }//GEN-LAST:event_jBagregarActionPerformed

    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel JLnombre;
    private javax.swing.JButton jBagregar;
    private javax.swing.JComboBox<String> jCBcargo;
    private javax.swing.JLabel jLcargo;
    private javax.swing.JLabel jLdireccion;
    private javax.swing.JLabel jLdni;
    private javax.swing.JLabel jLlegajo;
    private javax.swing.JLabel jLtel;
    private javax.swing.JTextField jTFdir;
    private javax.swing.JTextField jTFdni;
    private javax.swing.JTextField jTFlegajo;
    private javax.swing.JTextField jTFnom;
    private javax.swing.JTextField jTFtel;
    // End of variables declaration//GEN-END:variables
}
