/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interfaz;

import BD.Conexion;
import Clases.Empleado;
import java.sql.Connection;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

/**
 *
 */
public class PantallaEliminarEmp extends javax.swing.JFrame {

    /**
     * Creates new form PantallaEliminarEmp
     */
    public PantallaEliminarEmp() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLlegajo = new javax.swing.JLabel();
        jTFlegajobaja = new javax.swing.JTextField();
        jLtitulo = new javax.swing.JLabel();
        botonBaja = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLlegajo.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLlegajo.setText("Legajo");

        jTFlegajobaja.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTFlegajobajaKeyTyped(evt);
            }
        });

        jLtitulo.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLtitulo.setText("Ingrese el legajo del empleado que desea dar de baja");

        botonBaja.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        botonBaja.setText("Aceptar");
        botonBaja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonBajaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLtitulo)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(11, 11, 11)
                                .addComponent(jLlegajo)
                                .addGap(18, 18, 18)
                                .addComponent(jTFlegajobaja, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(185, 185, 185)
                        .addComponent(botonBaja)))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(jLtitulo)
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTFlegajobaja, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLlegajo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                .addComponent(botonBaja)
                .addGap(38, 38, 38))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void Eliminar(){
    
        if(jTFlegajobaja.getText().isEmpty()){
        JOptionPane.showMessageDialog(this, "Complete el campo.");  
         }else{
        Conexion con  = new Conexion();//creo la conexion
      
        try{
             Connection connect  = con.Conectar();//abro la conexion
             java.sql.Statement st = connect.createStatement(); //objeto para realizar la consulta
             String sql = "SELECT * FROM empleados WHERE elegajo = '"+jTFlegajobaja.getText()+"';";
              ResultSet rs = st.executeQuery(sql);
             if(rs.next()){ //SI SE ENCONTRARON LOS VALORES
             Empleado emp = new Empleado(rs.getString("enombre"),rs.getString("edni"),rs.getString("elegajo"),rs.getString("etel"),rs.getString("edireccion"),rs.getString("ecargo"));
                int opcion = JOptionPane.showOptionDialog(null, "DNI: "+ emp.getDni() + "\n" + "Nombre: "+ emp.getNombre() + "\n" + "Legajo: " + emp.getLegajo() + "\n" + "Teléfono: " + emp.getTelefono() + "\n" + "Dirección: " + emp.getDireccion() + "\n" + "Cargo: " + emp.getCargo() + "\n" + "¿Está seguro que desea dar de baja?", //contenido de la ventana
                         " " , //titulo de la ventana
                         JOptionPane.OK_CANCEL_OPTION, //para 2 botones 
                         JOptionPane.QUESTION_MESSAGE, //tipo de ícono
                         null,    // null para icono por defecto.
                         new Object[] { "Aceptar", "Cancelar"},//objeto para las opciones
                         "Aceptar"); //selección predeterminada
        if(opcion==0){
            sql = "DELETE FROM empleados WHERE elegajo = '"+jTFlegajobaja.getText()+"';";
            st.executeUpdate(sql); 
            JOptionPane.showMessageDialog(null,"Baja Exitosa.");   
        }  
           
            }else{
                JOptionPane.showMessageDialog(null,"Empleado no registrado.");
            }        
         st.close();
         connect = con.Cerrar();//Cierro la conexion
         jTFlegajobaja.setText("");
        this.setVisible(false);
        PantallaPrincipal p = new PantallaPrincipal();
        p.setVisible(true);
        }catch(Exception e)
        {
        JOptionPane.showMessageDialog(this, "Carga Fallida.");
        }
                }
    }
    
    
    private void botonBajaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonBajaActionPerformed
        // TODO add your handling code here:
        Eliminar();
       
    }//GEN-LAST:event_botonBajaActionPerformed

    private void jTFlegajobajaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTFlegajobajaKeyTyped
        // TODO add your handling code here:
         if(jTFlegajobaja.getText().length() >=6 ){ evt.consume(); }
    }//GEN-LAST:event_jTFlegajobajaKeyTyped

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonBaja;
    private javax.swing.JLabel jLlegajo;
    private javax.swing.JLabel jLtitulo;
    private javax.swing.JTextField jTFlegajobaja;
    // End of variables declaration//GEN-END:variables
}
