/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interfaz;

/**
 *
 * @author franco
 */
public class PantallaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form PantallaPrincipal
     */
    public PantallaPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BTNinicio = new javax.swing.JButton();
        BTNgestionE = new javax.swing.JButton();
        BTNcamiones = new javax.swing.JButton();
        BTNemporzona = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1050, 748));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BTNinicio.setContentAreaFilled(false);
        getContentPane().add(BTNinicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(85, 272, 70, 60));

        BTNgestionE.setContentAreaFilled(false);
        BTNgestionE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNgestionEActionPerformed(evt);
            }
        });
        getContentPane().add(BTNgestionE, new org.netbeans.lib.awtextra.AbsoluteConstraints(85, 382, 70, 60));

        BTNcamiones.setContentAreaFilled(false);
        BTNcamiones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNcamionesActionPerformed(evt);
            }
        });
        getContentPane().add(BTNcamiones, new org.netbeans.lib.awtextra.AbsoluteConstraints(85, 482, 70, 60));

        BTNemporzona.setContentAreaFilled(false);
        getContentPane().add(BTNemporzona, new org.netbeans.lib.awtextra.AbsoluteConstraints(85, 582, 70, 70));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/pmING1.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        jLabel1.setMinimumSize(new java.awt.Dimension(1050, 748));
        jLabel1.setPreferredSize(new java.awt.Dimension(1050, 748));
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 6, 1050, 725));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BTNcamionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNcamionesActionPerformed
       this.setVisible(false);
        new PantallaCamiones().setVisible(true);

    }//GEN-LAST:event_BTNcamionesActionPerformed

    private void BTNgestionEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNgestionEActionPerformed
        // TODO add your handling code here:
     ElegirCU elegir = new ElegirCU();
     elegir.setVisible(true);
     this.setVisible(false);
    }//GEN-LAST:event_BTNgestionEActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PantallaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PantallaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PantallaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PantallaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PantallaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BTNcamiones;
    private javax.swing.JButton BTNemporzona;
    private javax.swing.JButton BTNgestionE;
    private javax.swing.JButton BTNinicio;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
